---
title: "lab4B_AVVR_Data_Visualization_with_GGPlot"
author: "Andrew Romasco"
date: "9/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE)
```

This will go up through boxplots, and will be updated next week with more material.

```{r Loading Data}
library("tidyverse")
setwd("~/Andrew UMass Amherst Undergrad/Andrew Year 4 UMass/Fall 2020/Bio 597GE Genomics/genomics-course")
surveys_complete <- read_csv("data/surveys_complete.csv")
```

```{r}
ggplot(data = surveys_complete, aes(x = weight, y = hindfoot_length)) +
  geom_point()

## Or we could assign the plot by doing this...
surveys_plot <- ggplot(data = surveys_complete, 
                      mapping = aes(x = weight, y = hindfoot_length))
## Then graph the plot like this
#surveys_plot + 
#    geom_point()
```

## Hex Bin Challenge
```{r Hex Bin Challenge}
library("hexbin")
surveys_plot +
 geom_hex()

```

```{r Other options}
#Aplha adds transparency, color can hange the color
ggplot(data = surveys_complete, mapping = aes(x = weight, y = hindfoot_length)) +
    geom_point(alpha = 0.1, color = "blue")

#Can even use other variables in the graph
ggplot(data = surveys_complete, mapping = aes(x = weight, y = hindfoot_length)) +
    geom_point(alpha = 0.1, aes(color = species_id))

#Or use a boxplot
ggplot(data = surveys_complete, 
       mapping = aes(x = species_id, y = weight)) +
   geom_point(aes(color = plot_type))
```

```{r Box Plots}
#Jitter prevents points from overlapping
ggplot(data = surveys_complete, mapping = aes(x = species_id, y = weight)) +
    geom_boxplot(alpha = 0) +
    geom_jitter(alpha = 0.3, color = "tomato")

```

## Challenge Box Plot
```{r}
# With some added bits to make it look even better!
ggplot(data = surveys_complete, mapping = aes(x = species_id, y = hindfoot_length)) +
  aes(color = factor(plot_id)) +
  geom_violin(alpha = 0) +
  geom_jitter(alpha = 0.3) +
  scale_y_log10()
```

## Plotting Time Series

