---
title: "lab5_AVVR_COVID_Visualization"
author: "Andrew Romasco"
date: "9/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Loading Data}
library(tidyverse)
library(ggplot2)
setwd("~/Andrew UMass Amherst Undergrad/Andrew Year 4 UMass/Fall 2020/Bio 597GE Genomics/genomics-course")
Confirmed_State_3_13 <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-13-2020.csv")) %>%
  rename(Country_Region = "Country/Region", Province_State = "Province/State") %>% 
  filter (Country_Region == "US") %>% 
  group_by(Province_State, Country_Region) %>% 
  summarise(Confirmed = sum(Confirmed))

Confirmed_State_9_13 <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/09-13-2020.csv")) %>% 
  filter (Country_Region == "US") %>% 
  group_by(Province_State, Country_Region) %>% 
  summarise(Confirmed = sum(Confirmed)) 
```

```{r Clean Data}
setdiff(Confirmed_State_9_13$Province_State, Confirmed_State_3_13$Province_State)

Confirmed_State_9_13 <- Confirmed_State_9_13 %>% 
  filter(Province_State != "Recovered") 

Confirmed_State_3_13_9_13_joined <- full_join(Confirmed_State_3_13,
      Confirmed_State_9_13, by = c("Province_State"))

head(Confirmed_State_3_13_9_13_joined)
tail(Confirmed_State_3_13_9_13_joined, 5)

Confirmed_State_3_13_9_13_joined <- full_join(Confirmed_State_3_13,
      Confirmed_State_9_13, by = c("Province_State")) %>% 
      rename(Confirmed_3_13_2020 = "Confirmed.x", Confirmed_9_13_2020 = "Confirmed.y") %>% 
      select(-Country_Region.x, -Country_Region.y) %>% 
      replace_na(list(Confirmed_3_13_2020 = 0))

head(Confirmed_State_3_13_9_13_joined)
```

```{r}
#Make long or make wide
Confirmed_State_3_13_9_13_joined_long <- Confirmed_State_3_13_9_13_joined %>% 
              pivot_longer(-c(Province_State),
                            names_to = "Date", values_to = "Confirmed")

# to adjust figure size {r, fig.width = 5, fig.height = 10}
ggplot(Confirmed_State_3_13_9_13_joined_long, aes(x = Confirmed,  y = Province_State))  + 
    geom_point(aes(color = Date))

```

```{r Working with Time Series Data}
setwd("~/Andrew UMass Amherst Undergrad/Andrew Year 4 UMass/Fall 2020/Bio 597GE Genomics/genomics-course")
time_series_confirmed <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv")) %>%
  rename(Province_State = "Province/State", Country_Region = "Country/Region")
setwd("~/Andrew UMass Amherst Undergrad/Andrew Year 4 UMass/Fall 2020/Bio 597GE Genomics/genomics-course")
#Convert Data to long
time_series_confirmed_long <- time_series_confirmed %>% 
               pivot_longer(-c(Province_State, Country_Region, Lat, Long),
                            names_to = "Date", values_to = "Confirmed") 

#download.file(url="https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv", 
#               destfile = "data/time_series_covid19_deaths_global.csv")

time_series_deaths <- read_csv("data/time_series_covid19_deaths_global.csv")%>%
  rename(Province_State = "Province/State", Country_Region = "Country/Region")

#Convert to long
time_series_deaths_long <- time_series_deaths %>% 
               pivot_longer(-c(Province_State, Country_Region, Lat, Long),
                            names_to = "Date", values_to = "Deaths") 
#head(time_series_deaths_long)

#Join the Tables
time_series_confirmed_long <- time_series_confirmed_long %>% 
  unite(Key, Province_State, Country_Region, Date, sep = ".", remove = FALSE)

#head(time_series_confirmed_long)

time_series_deaths_long <- time_series_deaths_long %>% 
  unite(Key, Province_State, Country_Region, Date, sep = ".") %>% 
  select(Key, Deaths)

time_series_long_joined <- full_join(time_series_confirmed_long,
              time_series_deaths_long, by = c("Key")) %>% 
              select(-Key)
head(time_series_long_joined)
```

```{r Reformat the Date}
library(lubridate)
time_series_long_joined$Date <- mdy(time_series_long_joined$Date)
```

```{r Making Graphs}
time_series_long_joined_counts <- time_series_long_joined %>% 
  pivot_longer(-c(Province_State, Country_Region, Lat, Long, Date),
               names_to = "Report_Type", values_to = "Counts")

#head(time_series_long_joined_counts)

#Just the US
time_series_long_joined %>% 
  group_by(Country_Region,Date) %>% 
  summarise_at(c("Confirmed", "Deaths"), sum) %>% 
  filter (Country_Region == "US") %>% 
    ggplot(aes(x = Date,  y = Deaths)) + 
    geom_point() +
    geom_line() +
    ggtitle("US COVID-19 Deaths")

#Multiple other countries on different graphs
time_series_long_joined %>% 
  group_by(Country_Region,Date) %>% 
  summarise_at(c("Confirmed", "Deaths"), sum) %>% 
  filter (Country_Region %in% c("China","Japan", "Korea, South",
                                "Italy","Spain", "US")) %>% 
    ggplot(aes(x = Date,  y = Deaths)) + 
    geom_point() +
    geom_line() +
    ggtitle("COVID-19 Deaths") +
    facet_wrap(~Country_Region, ncol=2, scales="free_y")

#Multiple countries on the same graph
time_series_long_joined %>% 
    group_by(Country_Region,Date) %>% 
    summarise_at(c("Confirmed", "Deaths"), sum) %>% 
    filter (Country_Region %in% c("China","France","Italy", 
                                "Korea, South", "US")) %>% 
    ggplot(aes(x = Date,  y = Deaths, color = Country_Region)) + 
    geom_point() +
    geom_line() +
    ggtitle("COVID-19 Deaths")

#Confirmed and Deaths for the US on a logarithmic scale
time_series_long_joined_counts %>% 
  group_by(Country_Region, Report_Type, Date) %>% 
  summarise(Counts = sum(Counts)) %>% 
  filter (Country_Region == "US") %>% 
    ggplot(aes(x = Date,  y = log2(Counts), fill = Report_Type, color = Report_Type)) + 
    geom_point() +
    geom_line() +
    ggtitle("US COVID-19 Cases")
```

## Excersices

```{r 2-3, fig.width = 10, fig.height = 20}

ggplot(Confirmed_State_3_13_9_13_joined_long, aes(y = Province_State,  x = Confirmed))  + 
    geom_bar(stat = "identity",aes(color = Date)) +
  labs(x = "Confirmed Cases", 
       y = "State/Territory",
       title = "Confirmed Cases in the US")
```

```{r 4}
time_series_long_joined %>% 
  group_by(Date) %>% 
  summarise_at(c("Confirmed", "Deaths"), sum) %>% 
    ggplot(aes(x = Date,  y = Deaths)) + 
    geom_point() +
    ggtitle("Worldwide COVID-19 Deaths")
```

```{r 5-6}
# Mutate
total_time_long_joined <- time_series_long_joined %>% mutate(Deaths_Confirmed = Deaths + Confirmed)

ex6_plot <- total_time_long_joined %>% 
  group_by(Country_Region,Date) %>% 
  filter (Country_Region == "US") %>% 
    ggplot(aes(x = Date,  y = Deaths_Confirmed)) + 
    geom_point() +
    ggtitle("US COVID-19 Deaths and Confirmed Cases") +
    labs(x = "Date", 
       y = "Confirmed Cases and Deaths")

ex6_plot
```

```{r 7-8}
library(dplyr)
time_series_long_joined$Date <- as.Date(time_series_long_joined$Date)
  
data <- time_series_long_joined %>%
    group_by(Country_Region,Date) %>% 
    summarise_at(c("Confirmed", "Deaths"), sum) %>%
    filter(Date == "2020-09-20") %>%
    arrange(desc(Deaths)) %>%
    head(n=10)

highest <- data$Country_Region

time_series_long_joined %>% 
    group_by(Country_Region,Date) %>% 
    summarise_at(c("Confirmed", "Deaths"), sum) %>% 
    filter (Country_Region %in% highest) %>% 
    ggplot(aes(x = Date,  y = Deaths, color = Country_Region)) + 
    geom_point() +
    geom_line() +
    ggtitle("COVID-19 Deaths")
#Facet Wrapping
time_series_long_joined %>% 
    group_by(Country_Region,Date) %>% 
    summarise_at(c("Confirmed", "Deaths"), sum) %>% 
    filter (Country_Region %in% highest) %>% 
    ggplot(aes(x = Date,  y = Deaths, color = Country_Region)) + 
    geom_point() +
    geom_line() +
    ggtitle("COVID-19 Deaths") +
    facet_wrap(facets =  vars(Country_Region), nrow = 5, ncol = 2) +
    theme_dark()
```

```{r 9, fig.width = 10, fig.height = 58}
US_time_deaths <-read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_US.csv"))
US_time_deaths <- US_time_deaths[,7:255]

US_time_deaths_long <- US_time_deaths %>% 
               pivot_longer(-c(Province_State, Country_Region, Lat, Long_,Combined_Key,Population),
                            names_to = "Date", values_to = "Deaths")

US_time_deaths_long$Date <- mdy(US_time_deaths_long$Date)

US_time_deaths_long %>% 
  group_by(Province_State,Country_Region,Date) %>% 
    ggplot(aes(x = Date,  y = Deaths, color = Province_State)) + 
    geom_point() +
    geom_line() +
    labs(title = "COVID Deaths in US",
         x = "Date",
         y = "Deaths") +
    theme(legend.position = "none") +
    facet_wrap(facets =  vars(Province_State), nrow = 29, ncol = 2)

```


